### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by MareoRaft** [MareoRaft/MATH-Calc#2]
I think we need at least a few of these dependencies.  I think the other packages were successfully installed at one point and then cached.  It's suspicious and unclear what exactly is going on.

    tlmgr install: package amssymb not present in repository.
    tlmgr install: package amsthm not present in repository.
    tlmgr install: package color not present in repository.
    tlmgr install: package inputenc not present in repository.
    tlmgr install: package mathrsfs not present in repository.
    tlmgr install: package tikz not present in repository.
    tlmgr install: package upgreek not present in repository.

**Comment by MareoRaft** [comment]
(RE commit 60c594c4a85c9c40a26e74a07df6b8fbff724255)

**Comment by MareoRaft** [comment]
Well it's suspicious that there was an error on every single dependency I added.  This leads me to believe that these might be the *only* dependencies that aren't already preinstalled with latex when we first install it.  That's probably why they were the only dependencies I had in `.tex-dependencies` before, because they were the only ones we needed to install.

**Comment by ghseeli** [comment]
So, the package name need not be the same as the .sty file that is called in \usepackage. To figure out the correspondence, you do as follows: 

    $ tlmgr search --global --file amssymb.sty
    tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (not verified: gpg unavailable)
    amsfonts:
	    texmf-dist/tex/latex/amsfonts/amssymb.sty
    kotex-oblivoir:
	    texmf-dist/tex/latex/kotex-oblivoir/memhangul-x/xob-amssymb.sty

Thus, to get amssymb.sty, you have to add amsfonts to the `.tlmgr-dep` file.

**Comment by MareoRaft** [comment]
Do you mind running that command on each .sty name above?  My `tlmgr` isn't configured properly.

**Comment by ghseeli** [comment]
Well, why did you add these? Were pdfs not compiling correctly?

The reason I called the file `.tlmgr-dep` before was because some other TeX dependencies are installed in a separate place, so these are the dependencies that must be installed using tlmgr and not ubuntu.

**Comment by MareoRaft** [comment]
So the ones installed by Ubuntu are the builtin packages, and the ones installed by tlmgr are nonbuiltin dependencies?

**Comment by ghseeli** [comment]
I guess you could look at it that way. 

More accurately, Ubuntu repos maintain certain TeX bundles. The bundle we install in the .travis.yml using the Ubuntu repo (See the apt-get command) includes some of the really common packages, like amssymb. However, since we are fancy TeXers, we then use other packages, and so we run tlmgr to fill in the gaps.

**Comment by MareoRaft** [comment]
It is hard to know if PDFs have been produced successfully, because Travis can pass when there were actually errors with PDF production (for example, Travis build passed when textpos dependency was missing).

Perhaps we could capture PDF creation errors and report them at the end or force Travis to fail in that case.  I tried getting some .tex files to fail and they seem to consistently report the error

    pdflatex: Command for 'pdflatex' gave return code 256

as far as I can tell.

**Comment by MareoRaft** [comment]
We could change the compile line to:

    latexmk -pdf -interaction=nonstopmode || exit 1

or similar.

**Comment by ghseeli** [comment]
Hmmm, so there is some amount of philosophy here. I tend to prefer runs that let everything build and capture *all* the errors and report them at the end. Otherwise, you end up with this frustrating iterative process where you have to fix one error at a time and then wait for the next one. What I would prefer is if we piped the latexmk status into some sort of file and then parsed the file at the end. If there are any non-zero error codes, then travis can fail the build. Does that make sense?

**Comment by ghseeli** [comment]
Also, I don't understand this specific error; the PDFs seem to generate just fine.

**Comment by ghseeli** [comment]
Dependencies seem to be working now!
